import type {
  NodePC,
  Device,
  CommandPreset,
  CommandHistory,
  Task,
  Channel,
  Content,
  LogEntry,
  DeviceStatus,
} from "./types";

function generateDevices(nodeId: string, count: number): Device[] {
  const statuses: DeviceStatus[] = ["online", "running", "offline", "error"];
  const tasks = [
    "[MV] NewJeans - How Sweet",
    "aespa - Whiplash Offici...",
    "IVE - HEYA Official MV",
    "LE SSERAFIM - CRAZY",
    "SEVENTEEN - MAESTRO",
    null,
    null,
  ];

  return Array.from({ length: count }, (_, i) => {
    const status = statuses[Math.floor(Math.random() * 100) % 4];
    const hasTask = status === "running" || status === "online";
    return {
      id: `${nodeId}-D${String(i + 1).padStart(3, "0")}`,
      serial: `SN${nodeId.replace("PC-", "")}${String(i + 1).padStart(3, "0")}`,
      ip: `192.168.${parseInt(nodeId.replace("PC-", ""))}.${i + 10}`,
      status,
      currentTask: hasTask
        ? tasks[Math.floor(Math.random() * tasks.length)]
        : null,
      nodeId,
    };
  });
}

export const mockNodes: NodePC[] = [
  {
    id: "PC-01",
    name: "Node Alpha",
    ip: "10.0.1.1",
    status: "connected",
    devices: generateDevices("PC-01", 100),
  },
  {
    id: "PC-02",
    name: "Node Beta",
    ip: "10.0.1.2",
    status: "connected",
    devices: generateDevices("PC-02", 100),
  },
  {
    id: "PC-03",
    name: "Node Gamma",
    ip: "10.0.1.3",
    status: "connected",
    devices: generateDevices("PC-03", 100),
  },
  {
    id: "PC-04",
    name: "Node Delta",
    ip: "10.0.1.4",
    status: "connected",
    devices: generateDevices("PC-04", 100),
  },
  {
    id: "PC-05",
    name: "Node Epsilon",
    ip: "10.0.1.5",
    status: "disconnected",
    devices: generateDevices("PC-05", 100),
  },
];

export const mockPresets: CommandPreset[] = [
  {
    id: "cmd-001",
    name: "YouTube 앱 실행",
    type: "adb",
    command: "adb shell am start -n com.google.android.youtube/.HomeActivity",
    description: "YouTube 앱을 실행합니다",
    createdAt: "2026-02-10T09:00:00Z",
    updatedAt: "2026-02-10T09:00:00Z",
  },
  {
    id: "cmd-002",
    name: "스크린샷 캡처",
    type: "adb",
    command: "adb shell screencap -p /sdcard/screenshot.png",
    description: "현재 화면을 캡처하여 저장합니다",
    createdAt: "2026-02-09T14:30:00Z",
    updatedAt: "2026-02-11T08:00:00Z",
  },
  {
    id: "cmd-003",
    name: "자동 로그인 스크립트",
    type: "js",
    command: "node scripts/auto-login.js --target=${deviceId}",
    description: "접근성 API를 이용한 자동 로그인",
    createdAt: "2026-02-08T16:00:00Z",
    updatedAt: "2026-02-12T10:00:00Z",
  },
  {
    id: "cmd-004",
    name: "영상 재생 자동화",
    type: "js",
    command: "node scripts/play-video.js --videoId=${videoId}",
    description: "특정 영상을 자동으로 재생합니다",
    createdAt: "2026-02-07T11:00:00Z",
    updatedAt: "2026-02-11T15:00:00Z",
  },
  {
    id: "cmd-005",
    name: "네트워크 상태 확인",
    type: "adb",
    command: "adb shell ping -c 3 8.8.8.8",
    description: "디바이스 네트워크 연결 상태를 확인합니다",
    createdAt: "2026-02-06T09:00:00Z",
    updatedAt: "2026-02-06T09:00:00Z",
  },
  {
    id: "cmd-006",
    name: "앱 캐시 초기화",
    type: "adb",
    command: "adb shell pm clear com.google.android.youtube",
    description: "YouTube 앱의 캐시를 초기화합니다",
    createdAt: "2026-02-05T13:00:00Z",
    updatedAt: "2026-02-10T07:00:00Z",
  },
];

export const mockCommandHistory: CommandHistory[] = [
  {
    id: "ch-001",
    presetId: "cmd-001",
    presetName: "YouTube 앱 실행",
    targetNode: "PC-01",
    targetDevices: "1~20 디바이스",
    executedAt: "2026-02-12T10:30:00Z",
    status: "success",
  },
  {
    id: "ch-002",
    presetId: "cmd-003",
    presetName: "자동 로그인 스크립트",
    targetNode: "PC-02",
    targetDevices: "1~20 디바이스",
    executedAt: "2026-02-12T10:25:00Z",
    status: "running",
  },
  {
    id: "ch-003",
    presetId: "cmd-002",
    presetName: "스크린샷 캡처",
    targetNode: "PC-01, PC-03",
    targetDevices: "전체 기기",
    executedAt: "2026-02-12T09:45:00Z",
    status: "success",
  },
  {
    id: "ch-004",
    presetId: "cmd-005",
    presetName: "네트워크 상태 확인",
    targetNode: "PC-05",
    targetDevices: "1~10 디바이스",
    executedAt: "2026-02-12T08:00:00Z",
    status: "failed",
  },
];

export const mockTasks: Task[] = [
  {
    id: "task-001",
    title: "[MV] NewJeans - How Sweet",
    channelName: "HYBE LABELS",
    thumbnail: "https://img.youtube.com/vi/ArmDp-zijuc/mqdefault.jpg",
    duration: "3:27",
    videoId: "ArmDp-zijuc",
    status: "running",
    priority: 1,
    isPriority: true,
    assignedDevices: 18,
    totalDevices: 20,
    progress: 72,
    variables: {
      watchPercent: 85,
      commentProb: 12,
      likeProb: 45,
      saveProb: 8,
      subscribeToggle: true,
    },
    createdAt: "2026-02-12T09:00:00Z",
    completedAt: null,
    logs: [
      "2026-02-12 09:00 - 작업 시작",
      "2026-02-12 09:01 - 18개 디바이스 할당 완료",
      "2026-02-12 09:15 - 진행률 72%",
    ],
  },
  {
    id: "task-002",
    title: "aespa - Whiplash Official MV",
    channelName: "SMTOWN",
    thumbnail: "https://img.youtube.com/vi/jWQx2f-CErU/mqdefault.jpg",
    duration: "3:15",
    videoId: "jWQx2f-CErU",
    status: "queued",
    priority: 2,
    isPriority: false,
    assignedDevices: 0,
    totalDevices: 20,
    progress: 0,
    variables: {
      watchPercent: 70,
      commentProb: 8,
      likeProb: 35,
      saveProb: 5,
      subscribeToggle: false,
    },
    createdAt: "2026-02-12T08:30:00Z",
    completedAt: null,
    logs: ["2026-02-12 08:30 - 작업 대기열에 등록"],
  },
  {
    id: "task-003",
    title: "IVE - HEYA Official MV",
    channelName: "staraborned",
    thumbnail: "https://img.youtube.com/vi/eHha60r8ePQ/mqdefault.jpg",
    duration: "3:42",
    videoId: "eHha60r8ePQ",
    status: "completed",
    priority: 3,
    isPriority: false,
    assignedDevices: 20,
    totalDevices: 20,
    progress: 100,
    variables: {
      watchPercent: 90,
      commentProb: 15,
      likeProb: 50,
      saveProb: 10,
      subscribeToggle: true,
    },
    createdAt: "2026-02-12T06:00:00Z",
    completedAt: "2026-02-12T08:15:00Z",
    logs: [
      "2026-02-12 06:00 - 작업 시작",
      "2026-02-12 06:01 - 20개 디바이스 할당",
      "2026-02-12 08:15 - 작업 완료",
    ],
  },
  {
    id: "task-004",
    title: "LE SSERAFIM - CRAZY Official MV",
    channelName: "SOURCE MUSIC",
    thumbnail: "https://img.youtube.com/vi/LOo_C5HsdWg/mqdefault.jpg",
    duration: "3:09",
    videoId: "LOo_C5HsdWg",
    status: "completed",
    priority: 4,
    isPriority: false,
    assignedDevices: 20,
    totalDevices: 20,
    progress: 100,
    variables: {
      watchPercent: 60,
      commentProb: 5,
      likeProb: 30,
      saveProb: 3,
      subscribeToggle: false,
    },
    createdAt: "2026-02-11T22:00:00Z",
    completedAt: "2026-02-12T01:30:00Z",
    logs: [
      "2026-02-11 22:00 - 작업 시작",
      "2026-02-12 01:30 - 작업 완료",
    ],
  },
  {
    id: "task-005",
    title: "ILLIT - Magnetic Official MV",
    channelName: "HYBE LABELS",
    thumbnail: "https://img.youtube.com/vi/VACFR2uHxW8/mqdefault.jpg",
    duration: "2:58",
    videoId: "VACFR2uHxW8",
    status: "stopped",
    priority: 5,
    isPriority: false,
    assignedDevices: 12,
    totalDevices: 20,
    progress: 45,
    variables: {
      watchPercent: 50,
      commentProb: 10,
      likeProb: 40,
      saveProb: 6,
      subscribeToggle: true,
    },
    createdAt: "2026-02-11T18:00:00Z",
    completedAt: "2026-02-11T19:30:00Z",
    logs: [
      "2026-02-11 18:00 - 작업 시작",
      "2026-02-11 19:30 - 사용자에 의해 중단됨",
    ],
  },
  {
    id: "task-006",
    title: "SEVENTEEN - MAESTRO Official MV",
    channelName: "HYBE LABELS",
    thumbnail: "https://img.youtube.com/vi/GiLt4goAecc/mqdefault.jpg",
    duration: "4:01",
    videoId: "GiLt4goAecc",
    status: "queued",
    priority: 6,
    isPriority: false,
    assignedDevices: 0,
    totalDevices: 20,
    progress: 0,
    variables: {
      watchPercent: 75,
      commentProb: 10,
      likeProb: 38,
      saveProb: 7,
      subscribeToggle: false,
    },
    createdAt: "2026-02-12T10:00:00Z",
    completedAt: null,
    logs: ["2026-02-12 10:00 - 작업 대기열에 등록"],
  },
  {
    id: "task-007",
    title: "BTS - Dynamite Official MV",
    channelName: "HYBE LABELS",
    thumbnail: "https://img.youtube.com/vi/gdZLi9oWNZg/mqdefault.jpg",
    duration: "3:43",
    videoId: "gdZLi9oWNZg",
    status: "completed",
    priority: 7,
    isPriority: false,
    assignedDevices: 20,
    totalDevices: 20,
    progress: 100,
    variables: {
      watchPercent: 95,
      commentProb: 20,
      likeProb: 60,
      saveProb: 15,
      subscribeToggle: true,
    },
    createdAt: "2026-02-11T10:00:00Z",
    completedAt: "2026-02-11T14:00:00Z",
    logs: [
      "2026-02-11 10:00 - 작업 시작",
      "2026-02-11 14:00 - 작업 완료",
    ],
  },
];

export const mockChannels: Channel[] = [
  {
    id: "ch-yt-001",
    name: "HYBE LABELS",
    youtubeId: "UC3IZKseVpdzPSBaWxBxundA",
    thumbnail: "/placeholder-channel.jpg",
    subscriberCount: "76.4M",
    videoCount: 1842,
    addedAt: "2026-02-01T00:00:00Z",
    autoSync: true,
  },
  {
    id: "ch-yt-002",
    name: "SMTOWN",
    youtubeId: "UCEf_Bc-KVd7onSeifS3py9g",
    thumbnail: "/placeholder-channel.jpg",
    subscriberCount: "32.1M",
    videoCount: 4120,
    addedAt: "2026-02-01T00:00:00Z",
    autoSync: true,
  },
  {
    id: "ch-yt-003",
    name: "staraborned",
    youtubeId: "UCmUh55Hl-rOlMp78jYjItEg",
    thumbnail: "/placeholder-channel.jpg",
    subscriberCount: "18.7M",
    videoCount: 982,
    addedAt: "2026-02-05T00:00:00Z",
    autoSync: false,
  },
];

export const mockContents: Content[] = [
  {
    id: "cnt-001",
    videoId: "dQw4w9WgXcQ",
    title: "[MV] NewJeans - How Sweet",
    thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
    duration: "3:27",
    channelName: "HYBE LABELS",
    publishedAt: "2026-02-12T06:00:00Z",
    registeredAt: "2026-02-12T06:01:00Z",
    taskId: "task-001",
    status: "task_created",
  },
  {
    id: "cnt-002",
    videoId: "abc123",
    title: "aespa - Whiplash Official MV",
    thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
    duration: "3:15",
    channelName: "SMTOWN",
    publishedAt: "2026-02-12T04:00:00Z",
    registeredAt: "2026-02-12T04:01:00Z",
    taskId: "task-002",
    status: "task_created",
  },
  {
    id: "cnt-003",
    videoId: "def456",
    title: "IVE - HEYA Official MV",
    thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
    duration: "3:42",
    channelName: "staraborned",
    publishedAt: "2026-02-11T12:00:00Z",
    registeredAt: "2026-02-11T12:01:00Z",
    taskId: "task-003",
    status: "completed",
  },
  {
    id: "cnt-004",
    videoId: "ghi789",
    title: "SEVENTEEN - MAESTRO Official MV",
    thumbnail: "https://img.youtube.com/vi/dQw4w9WgXcQ/mqdefault.jpg",
    duration: "4:01",
    channelName: "HYBE LABELS",
    publishedAt: "2026-02-11T08:00:00Z",
    registeredAt: "2026-02-11T08:01:00Z",
    taskId: null,
    status: "pending",
  },
];

const logLevels = ["info", "warn", "error", "debug", "success"] as const;
const logSources = [
  "WebSocket",
  "TaskRunner",
  "DeviceManager",
  "ADB",
  "Scheduler",
  "API",
  "YouTubeSync",
];
const logMessages = [
  "디바이스 연결 확인 완료",
  "작업 큐에 새 작업이 추가되었습니다",
  "WebSocket 연결이 재설정되었습니다",
  "스크린샷 업로드 완료",
  "YouTube 채널 동기화 시작",
  "새 영상 감지: V-1032",
  "디바이스 D-015 연결 끊김 감지",
  "작업 task-001 진행률 갱신: 72%",
  "노드 PC-05 응답 없음 (타임아웃)",
  "접근성 입력 실패: 재시도 중...",
  "배치 명령 전송 완료 (20개 기기)",
  "네트워크 격리 확인: NET-A01",
  "데이터베이스 동기화 완료",
  "스케줄러 트리거: 다음 작업 시작",
  "메모리 사용량 경고: 85%",
];

export const mockLogs: LogEntry[] = Array.from({ length: 100 }, (_, i) => ({
  id: `log-${String(i + 1).padStart(4, "0")}`,
  timestamp: new Date(
    Date.now() - i * 30000 - Math.random() * 10000,
  ).toISOString(),
  level: logLevels[Math.floor(Math.random() * logLevels.length)],
  source: logSources[Math.floor(Math.random() * logSources.length)],
  nodeId: `PC-0${Math.floor(Math.random() * 5) + 1}`,
  deviceId:
    Math.random() > 0.4
      ? `D-${String(Math.floor(Math.random() * 100) + 1).padStart(3, "0")}`
      : null,
  message: logMessages[Math.floor(Math.random() * logMessages.length)],
}));
